// <auto-generated />
namespace TVApi.MigrationsApp
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddTest2Entity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTest2Entity));
        
        string IMigrationMetadata.Id
        {
            get { return "201604201428324_AddTest2Entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
